# Based on https://github.com/dbeaver/cloudbeaver
# server conf https://dbeaver.com/docs/cloudbeaver/Server-configuration/
# datasources https://dbeaver.com/docs/cloudbeaver/Configuring-server-datasources/

- name: Create cloudbeaver directory for generated files
  ansible.builtin.file:
    path: "{{ cloudbeaver_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_k8s_api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    common_namespace_name: cloudbeaver
    common_output_directory: "{{ cloudbeaver_output_directory }}"

- name: Prepare yaml file for PVC
  ansible.builtin.template:
    src: pvc.yaml.j2
    dest: "{{ cloudbeaver_output_directory }}/pvc.yaml"
    mode: u+rwx

- name: Add PVC
  kubernetes.core.k8s:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cloudbeaver_output_directory }}/pvc.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for Secrets
  ansible.builtin.template:
    src: secrets.yaml.j2
    dest: "{{ cloudbeaver_output_directory }}/secrets.yaml"
    mode: u+rwx

- name: Add Secrets
  kubernetes.core.k8s:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cloudbeaver_output_directory }}/secrets.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for anyuid RoleBinding
  ansible.builtin.template:
    src: anyuid-scc-rolebinding.yaml.j2
    dest: "{{ cloudbeaver_output_directory }}/anyuid-scc-rolebinding.yaml"
    mode: u+rwx

- name: Add anyuid RoleBinding
  kubernetes.core.k8s:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cloudbeaver_output_directory }}/anyuid-scc-rolebinding.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Prepare yaml file for Deployment
  ansible.builtin.template:
    src: deployment.yaml.j2
    dest: "{{ cloudbeaver_output_directory }}/deployment.yaml"
    mode: u+rwx

- name: Add Deployment
  kubernetes.core.k8s:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cloudbeaver_output_directory }}/deployment.yaml"
    wait: true
    wait_sleep: 10
    wait_timeout: 600

- name: Prepare yaml file for Service
  ansible.builtin.template:
    src: service.yaml.j2
    dest: "{{ cloudbeaver_output_directory }}/service.yaml"
    mode: u+rwx

- name: Add Service
  kubernetes.core.k8s:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    state: present
    force: false
    merge_type: merge
    src: "{{ cloudbeaver_output_directory }}/service.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_k8s_api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Crete Edge Route
  ansible.builtin.include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_k8s_api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    common_namespace_name: cloudbeaver
    common_route_name: cloudbeaver
    common_service_name: cloudbeaver
    common_wildcard_crt_path: "{{ cloudbeaver_wildcard_crt_path }}"
    common_wildcard_key_path: "{{ cloudbeaver_wildcard_key_path }}"
    common_ca_crt_path: "{{ cloudbeaver_ca_crt_path }}"
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ cloudbeaver_output_directory }}"

- name: Get cloudbeaver pod
  kubernetes.core.k8s_info:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    namespace: cloudbeaver
    label_selectors:
      - app=cloudbeaver
  register: cloudbeaver_pod

- name: Prepare yaml file for Secrets
  ansible.builtin.template:
    src: data-sources.json.j2
    dest: "{{ cloudbeaver_output_directory }}/data-sources.json"
    mode: u+rwx

- name: Copy mssql configuration to server
  kubernetes.core.k8s_cp:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    state: to_pod
    namespace: cloudbeaver
    pod: "{{ cloudbeaver_pod.resources[0].metadata.name }}"
    remote_path: /opt/cloudbeaver/workspace/GlobalConfiguration/.dbeaver/data-sources.json
    local_path: "{{ cloudbeaver_output_directory }}/data-sources.json"

- name: Delete cloudbeaver pod
  kubernetes.core.k8s:
    api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    api_version: v1
    kind: Pod
    state: absent
    namespace: cloudbeaver
    name: "{{ cloudbeaver_pod.resources[0].metadata.name }}"

- name: Wait for Cloudbeaver Deployment Available state
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_k8s_api_key: "{{ cloudbeaver_k8s_api_key | default(omit) }}"
    common_k8s_host: "{{ cloudbeaver_k8s_host | default(omit) }}"
    common_api_version: v1
    common_resource_kind: Deployment
    common_resource_name: cloudbeaver
    common_resource_namespace: cloudbeaver
    common_condition_name: Available
    common_retries: 36
    common_delay: 5
