- name: Manage DBs for BAN
  include_tasks: db/ban.yml

- name: Manage DBs for BAS
  include_tasks: db/bas.yml
  when: cp4ba_config.optional_components.bas

- name: Manage DBs for ODM
  include_tasks: db/odm.yml
  when: cp4ba_config.deployment_patterns.decisions

- name: Manage DBs for FNCM
  include_tasks: db/fncm.yml
  when: cp4ba_config.deployment_patterns.content

- name: Manage DBs for IER
  include_tasks: db/ier.yml
  when: cp4ba_config.deployment_patterns.content and cp4ba_config.optional_components.ier

- name: Manage DBs for AAE
  include_tasks: db/aae.yml
  when: cp4ba_config.deployment_patterns.application

- name: Manage DBs for AAE Data persistence
  include_tasks: db/aae-data-persistence.yml
  when: cp4ba_config.deployment_patterns.application and cp4ba_config.optional_components.ae_data_persistence

- name: Manage DBs for ADP
  include_tasks: db/adp.yml
  when: cp4ba_config.deployment_patterns.document_processing

- name: Manage DBs for BAWAUT
  include_tasks: db/bawaut.yml
  when: cp4ba_config.deployment_patterns.workflow and cp4ba_config.optional_components.baw_authoring
