- name: Remove Project postgresql
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ postgresql_k8s_api_key | default(omit) }}"
    host: "{{ postgresql_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: postgresql
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Remove RB postgresql-privileged
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ cerebro_k8s_api_key | default(omit) }}"
    host: "{{ cerebro_k8s_host | default(omit) }}"
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: postgresql-privileged
    wait: true
    wait_sleep: 15
    wait_timeout: 120
