- name: Remove Project pgadmin
  kubernetes.core.k8s:
    state: absent
    api_key: "{{ pgadmin_k8s_api_key | default(omit) }}"
    host: "{{ pgadmin_k8s_host | default(omit) }}"
    api_version: project.openshift.io/v1
    kind: Project
    name: pgadmin
    wait: true
    wait_sleep: 15
    wait_timeout: 120
